### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by RDIL** [cirrus-actions/discord#1]
- [x] Basic webhook
- [ ] Get on [`GitHub actions marketplace`](https://github.com/marketplace/actions)
- [x] Error if hook URL is null
- [x] Publish [`Docker`](https://docker.com) image
- [x] Use [`cirrus-actions`/`check-suite`](https://github.com/cirrus-actions/check-suite) to only send webhook if build exits with code `0`

**Comment by RDIL** [comment]
@fkorotkov check it out!
![https://images.rdil.rocks/34555510/52744733-7d52c400-2fab-11e9-82de-807bc5bac189.png](https://user-images.githubusercontent.com/34555510/52744733-7d52c400-2fab-11e9-82de-807bc5bac189.png)
we did it <o/  
[test server link](https://discord.gg/tcze8JN)

**Comment by fkorotkov** [comment]
You did it! Congrats! I will try to test it out tomorrow and will see if anything is missing for publishing to Marketplace. Congrats!

**Comment by RDIL** [comment]
Thanks :)  
I did notice that one thing is missing which is the marketplace developer agreement thing - I didn't want to sign it without your consent.

**Comment by fkorotkov** [comment]
@RDIL is there a way to include commit message in the payload?

It can be found via:

```bash
jq -r ".check_suite.head_commin.message" "$GITHUB_EVENT_PATH"
```

**Comment by RDIL** [comment]
Sure I can add that

**Comment by RDIL** [comment]
Preparing for archive until it can be updated to new system
